# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0005_auto_20160905_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='render_type',
            field=models.IntegerField(choices=[(1, 'Radio button'), (2, 'Quantity boxes'), (3, 'Product selector and quantity box'), (4, 'Checkbox button')], help_text='The registration form will render this category in this style.', verbose_name='Render type'),
        ),
    ]
