# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0010_auto_20160330_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeProfileBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrasion.Attendee')),
            ],
        ),
        migrations.RemoveField(
            model_name='badgeandprofile',
            name='attendee',
        ),
        migrations.DeleteModel(
            name='BadgeAndProfile',
        ),
    ]
