# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0014_attendee_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='access_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
