# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0016_auto_20160408_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='highest_complete_category',
        ),
        migrations.AddField(
            model_name='attendee',
            name='guided_categories_complete',
            field=models.ManyToManyField(to='registrasion.Category'),
        ),
    ]
