# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0020_auto_20160411_0258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryEnablingCondition',
            new_name='CategoryFlag',
        ),
        migrations.RenameModel(
            old_name='ProductEnablingCondition',
            new_name='ProductFlag',
        ),
        migrations.RenameModel(
            old_name='TimeOrStockLimitEnablingCondition',
            new_name='TimeOrStockLimitFlag',
        ),
        migrations.RenameModel(
            old_name='VoucherEnablingCondition',
            new_name='VoucherFlag',
        ),
        migrations.AlterModelOptions(
            name='categoryflag',
            options={'verbose_name': 'flag (dependency on product from category)', 'verbose_name_plural': 'flags (dependency on product from category)'},
        ),
        migrations.AlterModelOptions(
            name='productflag',
            options={'verbose_name': 'flag (dependency on product)', 'verbose_name_plural': 'flags (dependency on product)'},
        ),
        migrations.AlterModelOptions(
            name='timeorstocklimitflag',
            options={'verbose_name': 'flag (time/stock limit)', 'verbose_name_plural': 'flags (time/stock limit)'},
        ),
        migrations.AlterModelOptions(
            name='voucherflag',
            options={'verbose_name': 'flag (dependency on voucher)', 'verbose_name_plural': 'flags (dependency on voucher)'},
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Categories whose products are affected by this flag's condition.", to=b'registrasion.Category'),
        ),
        migrations.RenameField(
            model_name='enablingconditionbase',
            old_name='mandatory',
            new_name='condition',
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Disable if false'), (2, 'Enable if true')], default=2, help_text="If there is at least one 'disable if false' flag defined on a product or category, all such flag  conditions must be met. If there is at least one 'enable if true' flag, at least one such condition must be met. If both types of conditions exist on a product, both of these rules apply."),
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Products affected by this flag's condition.", to=b'registrasion.Product'),
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Categories whose products are affected by this flag's condition.", related_name='flagbase_set', to=b'registrasion.Category'),
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Products affected by this flag's condition.", related_name='flagbase_set', to=b'registrasion.Product'),
        ),
    ]
