# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0020_auto_20160411_0258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryEnablingCondition',
            new_name='CategoryFlag',
        ),
        migrations.RenameModel(
            old_name='ProductEnablingCondition',
            new_name='ProductFlag',
        ),
        migrations.RenameModel(
            old_name='TimeOrStockLimitEnablingCondition',
            new_name='TimeOrStockLimitFlag',
        ),
        migrations.RenameModel(
            old_name='VoucherEnablingCondition',
            new_name='VoucherFlag',
        ),
    ]
