# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0020_auto_20160411_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'inventory - category', 'verbose_name_plural': 'inventory - categories'},
        ),
        migrations.AlterModelOptions(
            name='discountitem',
            options={'ordering': ('product',)},
        ),
        migrations.AlterModelOptions(
            name='includedproductdiscount',
            options={'verbose_name': 'discount (product inclusions)', 'verbose_name_plural': 'discounts (product inclusions)'},
        ),
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='paymentbase',
            options={'ordering': ('time',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category__order', 'order'), 'verbose_name': 'inventory - product'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ('product',)},
        ),
        migrations.AlterModelOptions(
            name='timeorstocklimitdiscount',
            options={'verbose_name': 'discount (time/stock limit)', 'verbose_name_plural': 'discounts (time/stock limit)'},
        ),
        migrations.AlterModelOptions(
            name='voucherdiscount',
            options={'verbose_name': 'discount (enabled by voucher)', 'verbose_name_plural': 'discounts (enabled by voucher)'},
        ),
    ]
