# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0021_auto_20160411_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryflag',
            options={'verbose_name': 'flag (dependency on product from category)', 'verbose_name_plural': 'flags (dependency on product from category)'},
        ),
        migrations.AlterModelOptions(
            name='productflag',
            options={'verbose_name': 'flag (dependency on product)', 'verbose_name_plural': 'flags (dependency on product)'},
        ),
        migrations.AlterModelOptions(
            name='timeorstocklimitflag',
            options={'verbose_name': 'flag (time/stock limit)', 'verbose_name_plural': 'flags (time/stock limit)'},
        ),
        migrations.AlterModelOptions(
            name='voucherflag',
            options={'verbose_name': 'flag (dependency on voucher)', 'verbose_name_plural': 'flags (dependency on voucher)'},
        ),
    ]
