# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0021_auto_20160411_0748_squashed_0024_auto_20160411_2230'),
        ('registrasion', '0021_auto_20160411_0820'),
    ]

    operations = [
    ]
