# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('registrasion', '0023_auto_20160411_1001'), ('registrasion', '0024_auto_20160411_1002')]

    dependencies = [
        ('registrasion', '0022_auto_20160411_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Categories whose products are affected by this flag's condition.", to=b'registrasion.Category'),
        ),
        migrations.RenameField(
            model_name='enablingconditionbase',
            old_name='mandatory',
            new_name='condition',
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Disable if false'), (2, 'Enable if true')], default=2, help_text="If there is at least one 'disable if false' flag defined on a product or category, all such flag  conditions must be met. If there is at least one 'enable if true' flag, at least one such condition must be met. If both types of conditions exist on a product, both of these rules apply."),
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Products affected by this flag's condition.", to=b'registrasion.Product'),
        ),
    ]
