# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0022_merge'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([]),
        ),
    ]
