# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0023_auto_20160411_1001_squashed_0024_auto_20160411_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Categories whose products are affected by this flag's condition.", related_name='flagbase_set', to='registrasion.Category'),
        ),
        migrations.AlterField(
            model_name='enablingconditionbase',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Products affected by this flag's condition.", related_name='flagbase_set', to='registrasion.Product'),
        ),
    ]
