# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0023_auto_20160425_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Paid'), (3, 'Released')], db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='released',
        ),
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([('status', 'user'), ('status', 'time_last_updated')]),
        ),
    ]
