# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrasion', '0025_auto_20160425_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='entered_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
